Repository falcosecurity/kernel-crawler, pull requests merged in 2022-08, with the labels that each got.

#35 fix(crawler): made click.Choice options actually case sensitive.
  __init__.py
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, area/crawler

#38 fix(kernel_crawler): fixed ubuntu targets: actually use real ubuntu flavor as target
  kernel_crawler/ubuntu.py
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/crawler

#27 update(kernels): update kernel json lists.
  kernels/aarch64/list.json
  kernels/x86_64/list.json
Labels: dco-signoff: yes, approved, lgtm, size/XXL

#41 chore(kernels, readme): updated readme and dropped kernels lists that are now pushed to the kernels branch
  README.md
  kernels/README.md
  kernels/aarch64/README.md
  kernels/aarch64/list.json
  kernels/x86_64/README.md
  kernels/x86_64/list.json
Labels: dco-signoff: yes, approved, lgtm, kind/cleanup, size/XXL
