Repository falcosecurity/kernel-crawler, pull requests merged in 2022-05, with the labels that each got.

#3 update(README): updated badge link.
  README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#4 fix(CI): proper permissions on github action token.
  .github/workflows/update_kernels.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#5 chore(ci): switched on push for testing purposes.
  .github/workflows/update_kernels.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/ci

#6 fix(CI): update permissions on github action.
  .github/workflows/update_kernels.yaml
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, area/ci

#9 update(crawler): properly use amazonlinux2022 target for Al2022 driverkit output
  kernel_crawler/amazonlinux.py
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/crawler

#10 update(kernels): updated kernel json lists.
  kernels/aarch64/list.json
  kernels/x86_64/list.json
Labels: dco-signoff: yes, approved, lgtm, area/ci, size/XXL

#11 chore(CI): updated workflow file.
  .github/workflows/update_kernels.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/ci

#12 update(kernels): updated kernel json lists.
  kernels/aarch64/list.json
  kernels/x86_64/list.json
Labels: dco-signoff: yes, approved, lgtm, area/ci, size/XXL

#13 Changing to find_packages in setup.py
  setup.py
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, area/crawler

#14 update(kernels): updated kernel json lists.
  kernels/aarch64/list.json
  kernels/x86_64/list.json
Labels: dco-signoff: yes, approved, lgtm, kind/cleanup, area/ci, size/XXL
